#!/usr/bin/bash
xclip -selection clipboard -t image/png -o > "/home/bear/Pictures/$(date +%Y-%m-%d_%T).png"  # Use "Screenshot from $(date "+%Y-%m-%d %H-%M-%S").png" if you like GNOME filename format.
