#!/bin/bash
# connect-remote-audio.sh

SERVER_IP="100.105.48.61"

# Load server TCP module (if not already loaded)
ssh $SERVER_IP "pactl load-module module-native-protocol-tcp listen=0.0.0.0" 2>/dev/null

# Load tunnel source on client
pactl load-module module-tunnel-source server=tcp:$SERVER_IP:4713

sleep 1;

pw-link "tunnel-source.tcp:100.105.48.61:4713:receive_FR" "alsa_output.pci-0000_00_1f.3.analog-stereo:playback_FR"
pw-link "tunnel-source.tcp:100.105.48.61:4713:receive_FL" "alsa_output.pci-0000_00_1f.3.analog-stereo:playback_FL"

echo "Remote audio connected and routed to speakers"
